In [5]:
#Load data
import pandas as pd
import numpy as np
news_df = pd.read_csv("news.csv",sep=",")

In [6]:
#Preprocess data
import string
news_df['CATEGORY'] = news_df.CATEGORY.map({ 'b': 1, 't': 2, 'e': 3, 'm': 4 })
#news_df['TITLE'] = news_df.TITLE.map(str.maketrans('','', string.punctuation))
news_df= news_df.replace(np.nan, '', regex=True)
news_df.tail(6)

ID                                              TITLE  \
422413  422932  Cincinnati Children's surgeons to rebuild thro...   
422414  422933  Surgeons to remove 4-year-old's rib to rebuild...   
422415  422934  Boy to have surgery on esophagus after battery...   
422416  422935  Child who swallowed battery to have reconstruc...   
422417  422936  Phoenix boy undergoes surgery to repair throat...   
422418  422937  Phoenix boy undergoes surgery to repair throat...   

                                                      URL        PUBLISHER  \
422413  http://www.wsmv.com/story/26378648/surgeons-re...   WSMV Nashville   
422414  http://www.cbs3springfield.com/story/26378648/...          WSHM-TV   
422415  http://www.wlwt.com/news/boy-to-have-surgery-o...  WLWT Cincinnati   
422416  http://www.newsnet5.com/news/local-news/child-...     NewsNet5.com   
422417  http://www.wfsb.com/story/26368078/phoenix-boy...             WFSB   
422418  http://www.cbs3springfield.com/story/26368078/...          WSHM-TV   

        CATEGORY                          STORY                 HOSTNAME  \
422413         4  dpcLMoJD69UYMXMxaoEFnWql9YjQM             www.wsmv.com   
422414         4  dpcLMoJD69UYMXMxaoEFnWql9YjQM  www.cbs3springfield.com   
422415         4  dpcLMoJD69UYMXMxaoEFnWql9YjQM             www.wlwt.com   
422416         4  dpcLMoJD69UYMXMxaoEFnWql9YjQM         www.newsnet5.com   
422417         4  dpcLMoJD69UYMXMxaoEFnWql9YjQM             www.wfsb.com   
422418         4  dpcLMoJD69UYMXMxaoEFnWql9YjQM  www.cbs3springfield.com   

            TIMESTAMP Unnamed: 8  
422413  1409229189743             
422414  1409229190251             
422415  1409229190508             
422416  1409229190771             
422417  1409229191071             
422418  1409229191565

In [7]:
#Split into train and test data sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(news_df['TITLE'],news_df['CATEGORY'],random_state = 1)

print("Training dataset: ", X_train.shape[0])
print("Test dataset: ", X_test.shape[0])

Training dataset:  316814
Test dataset:  105605


In [8]:
#Extract features
from sklearn.feature_extraction.text import CountVectorizer

count_vector = CountVectorizer(stop_words = "english")
training_data = count_vector.fit_transform(X_train)
testing_data = count_vector.transform(X_test)

In [9]:
#Train Multinomial Naive Bayes classifier
from sklearn.naive_bayes import MultinomialNB
naive_bayes = MultinomialNB()
naive_bayes.fit(training_data, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [10]:
#Generate predictions
predictions = naive_bayes.predict(testing_data)
predictions

array([1, 1, 3, ..., 1, 1, 4], dtype=int64)

In [11]:
from sklearn.metrics import accuracy_score,precision_score, recall_score,f1_score
print("Accuracy Score:",accuracy_score(y_test, predictions) )
print("Precision Score:",precision_score(y_test, predictions,average="weighted") )
print(" Recall Score:", recall_score(y_test, predictions,average="weighted") )
print(" F1 Score:",f1_score(y_test, predictions,average="weighted") )

Accuracy Score: 0.9283367264807537
Precision Score: 0.9284613017362449
 Recall Score: 0.9283367264807537
 F1 Score: 0.9283906293365066


In [12]:
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(y_test, predictions))

Accuracy: 0.9283367264807537


In [14]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           1       0.91      0.91      0.91     29028
           2       0.90      0.91      0.90     27174
           3       0.97      0.96      0.96     38082
           4       0.92      0.92      0.92     11321

   micro avg       0.93      0.93      0.93    105605
   macro avg       0.92      0.92      0.92    105605
weighted avg       0.93      0.93      0.93    105605



In [13]:
from sklearn.metrics import confusion_matrix
print("confusion matrix is \n", confusion_matrix(y_test,predictions))

confusion matrix is 
 [[26306  1842   478   402]
 [ 1733 24703   496   242]
 [  547   717 36607   211]
 [  389   187   324 10421]]
