In [3]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import numpy as np
#categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
categories = ['comp.os.ms-windows.misc','misc.forsale','sci.space','talk.politics.mideast']
twenty_train = fetch_20newsgroups(subset='train',categories=categories,shuffle=True)
twenty_test = fetch_20newsgroups(subset='test',categories=categories,shuffle=True)
print(len(twenty_train.data))
print(len(twenty_test.data))
print(twenty_train.target_names)
print("\n".join(twenty_train.data[0].split("\n")))
print(twenty_train.target[0])
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_tf = count_vect.fit_transform(twenty_train.data)
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_tf)
X_train_tfidf.shape


2333
1554
['comp.os.ms-windows.misc', 'misc.forsale', 'sci.space', 'talk.politics.mideast']
From: jac2y@Virginia.EDU ("Jonathan A. Cook <jac2y>")
Subject: Stuff for sale- music
Organization: University of Virginia
Lines: 19

CDs ($9 ea inc shipping)
---
Jesus Jones, DOUBT
Residents, HEAVEN?
REM, DOCUMENT
Nymphs, SAD AND DAMNED single

Tapes
-----
Robert Plant, all solo stuff
Led Zeppelin IV

Tshirts
-------
Robert Plant, Manic Nirvana tour
Led Zeppelin, Symbols/Swansong black
Bob Dylan, 1990 tour tie-dye

All offers accepted.  Mail to jac2y@virginia.edu

1


(2333, 67419)

In [4]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn import metrics
mod = MultinomialNB()
mod.fit(X_train_tfidf, twenty_train.target)
X_test_tf = count_vect.transform(twenty_test.data)
X_test_tfidf = tfidf_transformer.transform(X_test_tf)
predicted = mod.predict(X_test_tfidf)
print("Accuracy:", accuracy_score(twenty_test.target, predicted))
print(classification_report(twenty_test.target,predicted,target_names=twenty_test.target_names))
print("confusion matrix is \n",metrics.confusion_matrix(twenty_test.target, predicted))

Accuracy: 0.9382239382239382
                         precision    recall  f1-score   support

comp.os.ms-windows.misc       0.94      0.90      0.92       394
           misc.forsale       0.99      0.90      0.94       390
              sci.space       0.91      0.97      0.94       394
  talk.politics.mideast       0.91      0.99      0.95       376

              micro avg       0.94      0.94      0.94      1554
              macro avg       0.94      0.94      0.94      1554
           weighted avg       0.94      0.94      0.94      1554

confusion matrix is 
 [[353   1  24  16]
 [ 16 350  12  12]
 [  4   1 382   7]
 [  2   0   1 373]]
